microsoft/AL-Go

.github/workflows/CI.yaml, Actions/AL-Go-Helper.ps1, Actions/AddExistingApp/action.yaml, Actions/CreateReleaseNotes/CreateReleaseNotes.ps1, Actions/CreateReleaseNotes/action.yaml, Actions/ReadSecrets/ReadSecrets.ps1, Actions/ReadSecrets/ReadSecretsHelper.psm1, Actions/RunPipeline/RunPipeline.ps1, Internal/freddydk.json, Templates/AppSource App/.github/workflows/CICD.yaml, Templates/AppSource App/.github/workflows/CreateTestApp.yaml, Templates/Per Tenant Extension/.github/workflows/CICD.yaml, Tests/AddExistingApp.Action.Test.ps1, Tests/CreateApp.Action.Test.ps1, Tests/CreateDevelopmentEnvironment.Action.Test.ps1, Tests/CreateReleaseNotes.Test.ps1, Tests/Deploy.Action.Test.ps1, Tests/IncrementVersionNumber.Action.Test.ps1, Tests/Mock-AL-Go-Helper.ps1, Tests/PipelineCleanup.Action.Test.ps1, Tests/ReadSecrets.Action.Test.ps1, Tests/ReadSettings.Action.Test.ps1, Tests/RunPipeline.Action.Test.ps1, Tests/TestActionsHelper.psm1, Tests/runtests.ps1
Support for using self-hosted runners.
=> Self Hosted Runner and more

Actions/AL-Go-Helper.ps1, Actions/AddExistingApp/AddExistingApp.ps1, Actions/CheckForUpdates/CheckForUpdates.ps1, Actions/CreateDevelopmentEnvironment/CreateDevelopmentEnvironment.ps1, Actions/Deploy/Deploy.ps1, Actions/PipelineCleanup/PipelineCleanup.ps1, Actions/RunPipeline/RunPipeline.ps1, Templates/AppSource App/.github/workflows/CICD.yaml, Templates/AppSource App/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml, Templates/AppSource App/.github/workflows/PublishToEnvironment.yaml, Templates/AppSource App/.github/workflows/UpdateGitHubGoSystemFiles.yaml, Templates/Per Tenant Extension/.github/workflows/CICD.yaml, Templates/Per Tenant Extension/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml, Templates/Per Tenant Extension/.github/workflows/PublishToEnvironment.yaml, Templates/Per Tenant Extension/.github/workflows/UpdateGitHubGoSystemFiles.yaml
Add parameter "Template to use" to the Update Al-Go System Files workflow
Support PTEs on embed apps
=> embed apps + template to use

Templates/AppSource App/.github/workflows/CICD.yaml, Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Starting a new CI on each push to main or release or any PR
any PR should start a CI build 
a push to a release branch or master should start a new build
=> Starting a new CI on each push to main or release or any PR

.github/workflows/Collect.yaml, Actions/AL-Go-Helper.ps1, Actions/CheckForUpdates/CheckForUpdates.ps1, Internal/Collect.ps1, Internal/Deploy.ps1, e2eTests/e2eTestHelper.psm1
=> Add Deploy/Collect workflows

README.md, Scenarios/AppDependencies.md
Adding docs on how to add a dependency to another repo
=> Addin docs for dependencies

Scenarios/BranchingStrategy.md
Just some very minor edits to get the Markdown Headings to display correctly.
=> Updated MD formatting in BranchingStrategy.md

e2eTests/e2eTestHelper.psm1
And use runs-on in private repos in end2end testing
=> Add support for runs-on setting

Actions/IncrementVersionNumber/IncrementVersionNumber.ps1
Hi folks,
This is to convert old version string to the Version type so that the Major and Minor properties can be updated.
**Steps to reproduce**
Run the Increment Version Number using `+0.1` as Updated Version Number parameter.
This also fixes the Create release workflow when the app version is incremented.
All tests passed.
Thanks!
=> Fix incremental app version change

Actions/AL-Go-Helper.ps1, Actions/ReadSettings/ReadSettings.ps1, Actions/RunPipeline/RunPipeline.ps1
**New settings**
DoNotSignApps - set to true to skip signing apps
DoNotPublishApps - set to true to skip publishing and testing apps (increases build performance)
ConditionalSettings - allow different settings for specific branches
```
Example:
"ConditionalSettings": [
{
"branches": [ 
"feature/*"
],
"settings": {
"doNotPublishApps":  true,
"doNotSignApps":  true
}
}
]
```
**CI/CD workflow**
- Apps are not signed when the workflow is running as a Pull Request validation
=> performance

README.md
Just some markdown formatting to improve readability of the links in the See also section.  Judging by the way you had formatted it originally I think you intended to have it as a list anyway?  Can cancel this PR if that wasn't the case.
Also used this as an exercise for following your steps outlined in "Contributing"
Before
After
=> Minor Formatting change to Readme,md

Actions/Deliver/Deliver.ps1, Actions/Deploy/Deploy.ps1, Actions/Github-Helper.psm1, Actions/ReadSettings/ReadSettings.ps1, Templates/AppSource App/.github/workflows/CICD.yaml, Templates/AppSource App/.github/workflows/PublishToEnvironment.yaml, Templates/Per Tenant Extension/.github/workflows/CICD.yaml, Templates/Per Tenant Extension/.github/workflows/PublishToEnvironment.yaml
Issue #193 Issue with "Publish To Environment" for mult-project repository
Issue #194 Issue with CICD step "Deploy" for multi-project repository
=> Better multi-project support

Templates/AppSource App/.github/workflows/PullRequestHandler.yaml, Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml
=> Issue #303

Actions/ReadSettings/ReadSettings.ps1
Fix for Issue #324 
Build all projects if any repo settings file have changed
=> Issue #324

Actions/AL-Go-Helper.ps1, Actions/RunPipeline/RunPipeline.ps1, RELEASENOTES.md, Scenarios/settings.md
Fix for Issue #319
Add AssignPremiumPlan setting to project settings file and transfer value to Run-AlPipeline
=> Issue #319

Actions/IncrementVersionNumber/IncrementVersionNumber.ps1
=> Create Release cannot find projects for incrementing version number

Actions/AL-Go-Helper.ps1, Templates/AppSource App/.AL-Go/cloudDevEnv.ps1, Templates/AppSource App/.AL-Go/localDevEnv.ps1, Templates/Per Tenant Extension/.AL-Go/cloudDevEnv.ps1, Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1
=> Ignore Quotes, plings and spaces when entering values in localDevEnv and cloudDevEnv

Actions/AL-Go-Helper.ps1, Actions/RunPipeline/RunPipeline.ps1, RELEASENOTES.md, Scenarios/settings.md
=> Add Setting for EnableTaskScheduler to create containers with Task Scheduler running

Templates/AppSource App/.AL-Go/cloudDevEnv.ps1, Templates/AppSource App/.AL-Go/localDevEnv.ps1, Templates/Per Tenant Extension/.AL-Go/cloudDevEnv.ps1, Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1
Issue #367
This looks to have been some kind of merge error.
Will put on my todo to add CI tests on LocalDevEnv and CloudDevEnv so that this doesn't happen again
=> LocalDevEnv.ps1 fails with "Cannot bind argument to parameter 'Path" because it is an empty string

Actions/ReadSettings/ReadSettings.ps1, Templates/AppSource App/.github/workflows/PullRequestHandler.yaml, Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml
This PR is fixing three issues with PR Handler: 
1. Getting the correct head sha 
2. Fix for using the wrong parameter name in action 
3. Stop skipping build task when pregate check is skipped
=> Fix issues with Pull Request Handler

Actions/CheckForUpdates/CheckForUpdates.ps1, Templates/AppSource App/.github/workflows/PullRequestHandler.yaml, Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml, e2eTests/e2eTestHelper.psm1, e2eTests/scenarios/BuildModes/runtest.ps1, e2eTests/scenarios/GitHubPackages/runtest.ps1, e2eTests/scenarios/ReleaseBranches/runtest.ps1
1. Update AL Go System files cannot downgrade due to missing Outputs under Initialization in old version.
2. PR handler needs access to GitHubPackagesContext in order to resolve dependencies
=> Issue #427 - Dependencies to GitHub Packages are not included in PR handler

Actions/AL-Go-Helper.ps1, Actions/Github-Helper.psm1, RELEASENOTES.md
Issue #434 
`gh auth status --show-token` changed output format (added another line)
this fix will grab one line only.
=> Issue #434

Actions/AL-Go-Helper.ps1
=> fix for #451

RELEASENOTES.md, Templates/AppSource App/.github/workflows/CreateRelease.yaml, Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml
This regression was introduced when we removed dependencies to deprecated node.js v12
Before:
After:
=> Fix for issue #446

Actions/AL-Go-Helper.ps1
didn't get the second -recurse added based on the review
=> add recurse

Actions/AL-Go-Helper.ps1, Actions/Github-Helper.psm1, RELEASENOTES.md
Instead of using gh auth status --show-token and retrieve the token using string manipulation.
=> use gh auth token to retrieve auth token

Actions/CreateApp/AppTemplate/app.json, RELEASENOTES.md, e2eTests/appsourceapp/My App.Test/app.json, e2eTests/appsourceapp/My App/app.json, e2eTests/e2eTestHelper.psm1, e2eTests/pte/My App.Test/app.json, e2eTests/pte/My App/app.json
Fix for Issue #501
Change default application dependency in Create New App to 22.0.0.0 and include the feature NoImplicitWith.
=> Change application dependency to 22.0.0.0

.github/workflows/Deploy.yaml
=> Add run-name for Deploy workflow

.github/workflows/E2E.yaml, e2eTests/Test-AL-Go-Upgrade.ps1, e2eTests/Test-AL-Go.ps1, e2eTests/Test-Functions.ps1
This PR solves the test failures caused by the double CI/CD runs.
=> GitHub issue

e2eTests/e2eTestHelper.psm1, e2eTests/scenarios/ReleaseBranches/runtest.ps1
E2E Test failure from jobname change
=> Fix E2E test failure

Actions/Github-Helper.psm1
Issue #577
Give better error message if Git or GH is missing on self-hosted runners.
=> give better error message

Scenarios/RegisterProductionEnvironment.md
=> Fix documentation

Scenarios/SetupPowerPlatform.md, Scenarios/TryPowerPlatformSamples.md
Update the set up steps based on customer feedback.
=> Update Power Platform set up steps

Actions/Sign/Sign.ps1, Actions/Sign/action.yaml, Tests/Sign.Test.ps1
Bug in preview, Sign cannot run due to a mandatory parameter not being transferred.
=> Issue #653

RELEASENOTES.md, Templates/AppSource App/.github/workflows/_BuildALGoProject.yaml, Templates/Per Tenant Extension/.github/workflows/_BuildALGoProject.yaml
=> GitHub Variables ALGoRepoSettings and ALGoOrgSettings are not applied during build

Actions/AL-Go-Helper.ps1
=> Code signing in Preview with HSM fails after Update

Actions/Deploy/Deploy.ps1
Currently there is already an option to run the CI/CD pipline (and create packages) from different than main branch. It would be complementary to also be able to deploy this packages from different branches.
=> Possibility to deploy from selected branches

Actions/Deploy/Deploy.ps1
CI/CD pipline creates packages with modified branch name. Get-Artifacts function also requires this modified name for artifactPattern
=> Possibility to deploy from selected branches - fix

e2eTests/scenarios/IncludeDependencies/runtest.ps1, e2eTests/scenarios/SpecialCharacters/runtest.ps1
Two tests was apparently using an organizational token which I deleted some days ago.
=> Bug in E2E tests

Actions/AL-Go-Helper.ps1, RELEASENOTES.md
=> release notes

Actions/Github-Helper.psm1
Fix for https://github.com/microsoft/AL-Go/issues/785
=> fix getartfacts

RELEASENOTES.md, Templates/AppSource App/.gitignore, Templates/Per Tenant Extension/.gitignore
=> add .altestrunner to gitignore

Workshop/PublishToProduction.md
=> Nomenclature

Actions/AL-Go-Helper.ps1, Actions/RunPipeline/RunPipeline.ps1, Scenarios/settings.md
Pending on https://github.com/microsoft/navcontainerhelper/pull/3292 and BcContainerHelper preview release.
=> Propage enableCodeAnalyzersOnTestApps setting to Run-AlPipeline

Scenarios/UpdateAlGoSystemFiles.md
=> improve doc

Actions/IncrementVersionNumber/IncrementVersionNumber.psm1, Tests/IncrementVersionNumber.Action.Test.ps1, e2eTests/scenarios/ReleaseBranches/runtest.ps1
- Change updateVersion value to +1 in E2E tests
- Always set build and revision numbers to 0
=> Fix E2E tests

Templates/AppSource App/.github/workflows/CreateRelease.yaml, Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml
Add run-name to Create Release workflow
Fixes #996
=> Add run-name to create release

.github/workflows/Deploy.yaml, Internal/Deploy.ps1, RELEASENOTES.md
Automate:
- The generation of modifying release notes with the version number (and revert)
- Creation of a release in AL-Go repo
Adds:
- Check that a successful end 2 end test was run on the same commit you are releasing
=> Automate release process

.github/workflows/E2E.yaml, e2eTests/e2eTestHelper.psm1
End 2 end tests on private repos was using self-hosted agents, which no longer are there.
=> End 2 end tests

Actions/Deliver/Deliver.ps1, RELEASENOTES.md
Fail delivery if New-AppSourceSubmission fails.
Fixes #1073
=> Issue 1073

Actions/Deliver/Deliver.ps1
This fix https://github.com/microsoft/AL-Go/pull/1118 introduced a bug, causing an end 2 end test failure
=> End 2 End test failure

.github/dependabot.yml
As per https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories
=> Use directories property in dependabot.yml

RELEASENOTES.md
Add release notes for telemetry module
=> Add release notes for telemetry module

Actions/ReadSecrets/ReadSecrets.ps1, Actions/ReadSecrets/ReadSecretsHelper.psm1, RELEASENOTES.md
=> Issue 1164

Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1
Improve error message in Update AL Go System Files
Fixes #1204
=> Improve error message in Update AL Go System Files

Scenarios/CreateOnlineDevEnv2.md
Fixes #1347
Update documentation to not use retired BCContainerhelper command
=> Update documentation to not use retired BCContainerhelper command

Templates/AppSource App/.github/workflows/IncrementVersionNumber.yaml, Templates/Per Tenant Extension/.github/workflows/IncrementVersionNumber.yaml
Move write permissions on job level in IncrementVersionNumber.yaml
=> Move write permissions on job level in IncrementVersionNumber.yaml

.github/workflows/powershell.yaml, Actions/RunPSScriptAnalyzer/RunPSScriptAnalyzer.ps1, Actions/RunPSScriptAnalyzer/action.yml
The excludeRule parameter is not working correctly, resulting in code scanning alerts not being suppressed.
=> Additional debug messages.

Actions/RunPipeline/RunPipeline.ps1
Regression after latest PR (Workshop Feedback)
=> Only check URLs

RELEASENOTES.md, Templates/AppSource App/.github/workflows/CreateRelease.yaml, Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml
=> Create Release fails due to recent changes to the AL-Go

Actions/DetermineDeploymentEnvironments/DetermineDeploymentEnvironments.ps1, Actions/RunPipeline/RunPipeline.ps1, RELEASENOTES.md
=> Publish to Environment - DependencyInstallMode not found

Actions/TelemetryHelper.psm1
=> Use temp folder for App Insights DLLs

Actions/ReadSecrets/ReadSecrets.ps1, Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml
=> Get accesstoken for Create Release

Scenarios/settings.md
Add doc for `PreCompileApp` and `PostCompileApp` scripts.
=> Add doc for PreCompileApp and PostCompileApp

e2eTests/Test-AL-Go.ps1, e2eTests/Workflows/RunCreateRelease.ps1, e2eTests/scenarios/ReleaseBranches/runtest.ps1
End 2 End tests are failing due to some refactoring.
This fixes the tests.
=> end 2 end test failures

Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1, Tests/CheckForUpdates.Action.Test.ps1
=> Fix issue with transfering $schema propery when destination file does't exist

Templates/AppSource App/.AL-Go/cloudDevEnv.ps1, Templates/AppSource App/.AL-Go/localDevEnv.ps1, Templates/Per Tenant Extension/.AL-Go/cloudDevEnv.ps1, Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1
=> Dowload settings schema in localDevEnv and cloudDevEnv

.github/workflows/StaleIssues.yml
Utilize https://github.com/actions/stale/
=> Add workflow to mark stale issues

.devcontainer/devcontainer.json
Add GitHub MCP server to codespace settings
=> Add GitHub MCP server to codespace settings

Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1, Actions/Github-Helper.psm1
Hotfix for 7.3 with additional debug logs for issue regarding CheckForUpdates fail.
=> Hotfix: Additional debugging for 7.3

RELEASENOTES.md, Scenarios/secrets.md
A few minor things I ran into while performing a training session in Madrid
=> A few minor doc. things found in Madrid

Actions/Deploy/Deploy.ps1, Actions/Deploy/Deploy.psm1, RELEASENOTES.md, Tests/Deploy.Module.Test.ps1
Apply buildMode when filtering apps during deployment
Related to issue: #1926
=> Apply buildMode when filtering apps during deployment
