microsoft/AL-Go

Actions/CheckForUpdates/CheckForUpdates.ps1
Actions/CheckForUpdates/README.md
Actions/CheckForUpdates/action.yaml

Issue: Running the "Update AL-Go System Files" with `directCommit` set to 'Y' always creates a PR that targets the main branch insted of the branch the action was invoked on.
Solution: Add an `updateBranch` parameter to `CheckForUpdates` action and corresponding script to use as a target branch when creating a PR with the updates. By default, the `updateBranch` should be the branch the action is run on.

Add updateBranch parameter to CheckForUpdates action

---

Actions/AL-Go-Helper.ps1
Actions/Deliver/Deliver.ps1
Actions/ReadSettings/ReadSettings.ps1
Actions/ReadSettings/action.yaml
Actions/RunPipeline/RunPipeline.ps1
Actions/RunPipeline/action.yaml
RELEASENOTES.md
Scenarios/settings.md
Templates/AppSource App/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Tests/ReadSettings.Action.Test.ps1

Adding support for build modes. Initial support the following build modes: 
- **Translated** - Running a build with 'translationfile' as a compiler feature
- **Clean** - Applying a set of _preprocessorsymbols_ during compilation. The list of _preprocessorsymbols_ is defined in the settings.json of the AL-GO project 
- **Default** - Running a build with the code as it is.
Default build mode is 🥁...  **Default**

Add support for build modes 

---

Actions/AL-Go-Helper.ps1

AnalyzeRepo shows a false warning when a folder contains both folders and files.

Buildmodulesseperately

---

RELEASENOTES.md
Templates/AppSource App/.AL-Go/cloudDevEnv.ps1
Templates/AppSource App/.AL-Go/localDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/cloudDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1

With the latest changes in ContainerHelper to support PS7, we can now run localDevEnv and cloudDevEnv directly in VS Code (instead of spawning a PS5.1 powershell prompt with all the problems that gives).
Fix for Issue #215

Run LocalDevEnv and CloudDevEnv in VS Code

---

Actions/AL-Go-Helper.ps1
Actions/CheckForUpdates/CheckForUpdates.ps1
RELEASENOTES.md
Scenarios/settings.md

Issue #318
Add new Repo setting: unusedALGoSystemFiles in which you can specify an array of System Files, which won't be updated, but instead will be removed.
Example here: https://github.com/BusinessCentralApps/BingMaps.AppSource/blob/main/.github/AL-Go-Settings.json

Issue #318

---

Actions/AL-Go-Helper.ps1

The addition of AssignPremiumPlan was not affecting LocalDevEnv, but only the build pipelines

Add AssignPremiumPlan when using LocalDevEnv

---

Actions/AL-Go-Helper.ps1
Actions/AL-Go-TestRepoHelper.ps1
Actions/AddExistingApp/AddExistingApp.ps1
Actions/CheckForUpdates/CheckForUpdates.ps1
Actions/CreateApp/AppHelper.psm1
Actions/CreateApp/CreateApp.ps1
Actions/Deliver/Deliver.ps1
Actions/Deploy/Deploy.ps1
Actions/ReadSecrets/ReadSecrets.ps1
Actions/ReadSettings/ReadSettings.ps1
Actions/RunPipeline/RunPipeline.ps1
Actions/WorkflowInitialize/WorkflowInitialize.ps1
README.md
RELEASENOTES.md
Templates/AppSource App/.AL-Go/cloudDevEnv.ps1
Templates/AppSource App/.AL-Go/localDevEnv.ps1
Templates/AppSource App/.github/workflows/CICD.yaml
Templates/AppSource App/.github/workflows/PublishToEnvironment.yaml
Templates/Per Tenant Extension/.AL-Go/cloudDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1
Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/PublishToEnvironment.yaml
Tests/AL-Go-Helper.Test.ps1

Issue #171 create a workspace file when creating a project
Issue #356 Publish to AppSource fails in multi project repo
ReadSettings has been refactored to allow organization wide settings to be added as well. CI Tests have been added to cover ReadSettings.
The primary change is to ensure that $baseFolder is always the $baseFolder and $projectFolder is always a project folder (they are the same in a single project repo).
ReadSettings and more now have two parameters: baseFolder and project - which clearly specifies when to read project settings files and when to read repo settings files only
Comments have been added to ReadSettings and MergeCustomObjectIntoOrderedDictionary

Refactor ReadSettings and add tests

---

.github/workflows/CI.yaml
Tests/ActionOrigin.Test.ps1
Tests/ActionOriginTest/ActionOrigin.Test.ps1
Tests/TestActionsHelper.psm1

To make sure we don't accidently add references to forks of AL-GO-Actions, we should have a gate that checks for references to AL-GO-Actions. In this gate we should check if all workflows that are using AL-GO-Actions, are using them from microsoft/AL-GO-Actions

Verify origin of AL-GO actions in PR 

---

Tests/TestActionsHelper.psm1

The test is calling the wrong function name

Verify actions fix

---

Templates/AppSource App/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml

Use default run name for CICD workflows as Github already sets the run-name to the commit message if the action is triggered on push (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name)

Use default run name for CICD workflows

---

Actions/CheckForUpdates/CheckForUpdates.ps1
Templates/AppSource App/.github/workflows/CICD.yaml
Templates/AppSource App/.github/workflows/Current.yaml
Templates/AppSource App/.github/workflows/NextMajor.yaml
Templates/AppSource App/.github/workflows/NextMinor.yaml
Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/Current.yaml
Templates/Per Tenant Extension/.github/workflows/NextMajor.yaml
Templates/Per Tenant Extension/.github/workflows/NextMinor.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml

Enable concurrency groups in Pull Request Handler. This way there's only one PR Build running at a time per PR, and if there's a new push to the PR while a PR Build is running, that PR build will be cancelled.

Enable concurrency groups in Pull Request Handler

---

Actions/AL-Go-Helper.ps1

When scanning for apps in an AL-Go project, the process should look into `appFolders` and `testFolders` (if defined).

Use appFolders and testFolders to determine project dependencies

---

Actions/CreateReleaseNotes/CreateReleaseNotes.ps1
RELEASENOTES.md

CreateReleaseNotes will check that the tag specified is SemVer, but the error will be ignored and the branch value is never set.
If the version isn't SemVer, the action should fail - not ignore the error and fail later down the line.

Issue #391 Create release action - CreateReleaseBranch error

---

Actions/AL-Go-Helper.ps1

Due to what I see as an error in PowerShell, ordered dictionaries cast into a HashTable will become a case sensitive HashTable. This PR will copy the potentially wrong HashTable to ensure we have a case insensitive HashTable.

Issue #385 Ensure case insensitivity

---

Actions/AL-Go-Helper.ps1
Scenarios/settings.md

This parameter was forgotten when creating the dependency resolution feature, and I have a partner who needs to override this

Support override of InstallMissingDependencies

---

Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml

Both _Publish artifacts - build output_ and _Publish artifacts - container event log_ steps should be part of the _PullRequest Build_ workflow as it contains a build job.
Most probably they were omitted when CICD workflow was split.

Add "Publish artifacts - container event log" and "Publish artifacts - build output" to PullRequest Build workflow

---

Templates/AppSource App/.AL-Go/localDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1

Fix for localDevEnv.ps1, enabling the script execution with parameter licenseFileUrl = "none".

Fix licenseFileUrl = "none" param in localDevEnv 

---

Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml

Sometimes it can be an issue that the PR Build is not running with the latest changes from the base branch. This build https://github.com/microsoft/ALAppExtensions/actions/runs/4500507606 is complaining about breaking changes even though, the PR doesn't touch the SignedXml codeunit. The issue here is that the head branch doesn't contain all the latest changes from the base branch. 
A fix for this could be to use the merge branch created by GitHub since it contains the changes from both head and base branch.

Run PR Build based on merge commit 

---

Actions/AL-Go-Helper.ps1

fix for issue #463
Reason for this bug is that $basefolder sometimes is with / instead of \ - i.e. the comparison returns false.
Using Join-Path to resolve the $basefolder path to the same format as the projectFolder.

Issue #463

---

Actions/AL-Go-Helper.ps1

Running localdevenv from ALAppExtensions right now is throwing the following error:
```
Error: The appProjectFolder (D:\a\_work\1\s\Modules\DevTools\TestFramework\TestStabilityTools\PreventMetadataUpdates) is not shared with the container.
Stacktrace: at Compile-AppInBcContainer, C:\Users\cloudtest\AppData\Local\Temp\485e71ec-f9de-495d-8bd2-d87b27f5977a\BcContainerHelper\AppHandling\Compile-AppInNavContainer.ps1: line 134
at <ScriptBlock>, D:\a\_work\1\s\Build\Scripts\CompileAppInBcContainer.ps1: line 32
at <ScriptBlock>, D:\a\_work\1\s\Test Stability Tools\.AL-Go\CompileAppInBcContainer.ps1: line 7
at <ScriptBlock>, C:\Users\cloudtest\AppData\Local\Temp\485e71ec-f9de-495d-8bd2-d87b27f5977a\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1753
at <ScriptBlock>, …
```

Add sharedfolder when running CreateDevEnv

---

Actions/ReadSecrets/ReadSecrets.ps1
RELEASENOTES.md

Fix for Issue #453
When reading secrets, the list of secrets to get might contain duplicates, resolving in an exception.
This fix ensures that each secret is only read once.

Issue #453

---

Actions/AL-Go-Helper.ps1
Actions/RunPipeline/RunPipeline.ps1

Non-existing appFolders or appFolders, which didn't contain an app.json should just be ignored, but display a warning.
Before this PR, appFolders which doesn't exist would give:
After this PR, appFolders which doesn't exists will be ignored and give:
Additionally, this warning has been removed:
No reason to warn about things people have decided.

Give warning when appFolders doesn't exist

---

Actions/AL-Go-Helper.ps1
Actions/CheckForUpdates/CheckForUpdates.ps1

Fix for issue #497
After the latest change in Update AL-Go System Files to use ReadSettings instead of just reading the config file, the repoSettings now became a OrderedDictionary, which is case sensitive.
This PR changes the ConvertTo-HashTable to also be able to recursively convert a HashTable or an OrderedDictrionary to a new HashTable - and then use that in AL-Go System Files.
I will add a todo to see if we can make a test to test for case sensitivity in settings files.
This change shouldn't have any side effects, but running End-2-End tests now to ensure that I am right.

UpdateSystemFiles fails in preview

---

Actions/AL-Go-Helper.ps1

Issue #508 is an error in ConvertTo-HashTable in BcContainerHelper, but the same function exists in AL-Go-Helper.ps1
$_ is an object containing various properties and not the name of the property - we should check for the type of $_.value

Issue #508

---

Actions/AL-Go-Helper.ps1
Actions/Deploy/Deploy.ps1
Actions/ReadSettings/ReadSettings.ps1
Actions/ReadSettings/action.yaml
Templates/AppSource App/.github/workflows/PublishToEnvironment.yaml
Templates/Per Tenant Extension/.github/workflows/PublishToEnvironment.yaml
Tests/ReadSettings.Action.Test.ps1

In the current preview bits, Publish to Environment will ask for authentication after the initialize step if you are requesting to deploy to a single environment, which is created in GitHub Environments and the AUTHCONTEXT secret is created under the environment as an environment secret.
The reason for this is, that this secret is NOT available during initialize and as such, we think we need to authenticate.
This fix causes us to only ask for authentication to unknown environments (which kind of was the entire idea)

Only ask for authentication if the environment doesn't exist.

---

Actions/CheckForUpdates/CheckForUpdates.ps1

Branch name is too random and creates a mess of branches (in the cases when they are not automatically deleted, when the corresponding PR is merged).
New branch name: `$updateBranch/update-al-go-system-files/$((Get-Date).ToUniversalTime().ToString("yyMMddHHmmss"))`
E.g.
`main/update-al-go-system-files/210101120000`
`releases/1.0/update-al-go-system-files/230508152112`
`my-feature-branch/update-al-go-system-files/220101131201`

Improve branch name when updating AL-Go system files

---

Actions/AL-Go-Helper.ps1

Fix for issue #513
Allow people to add a setting to use a different version of containerhelper.
Give a warning if they decide to use an older version.
Reason for this is that we has one case, where the latest version had a bug, and the partner could temporarily use an old version to get by.
This also allows people to always use preview (even in latest)
Using "4.0.16" looks like:
Using "preview" looks like:
No setting looks like:
Latest might still get different versions from the CDN after a release (if we don't purge the CDN) - but that shouldn't matter

Allow to override bcContainerHelper version

---

Actions/Github-Helper.psm1
Actions/ReadSecrets/ReadSecrets.ps1
Actions/ReadSecrets/ReadSecretsHelper.psm1

This is a fix for issue #491
The reason for this is really that the target repository was renamed, but GitHub handles that in all other cases by redirecting you.
This fix will locate the artifacts needed in the new repository and issue a warning that the repository was renamed or moved.
This PR also relaxes the fields that get masked from StorageContext, as these strings might be reused elsewhere.

Issue #491 - Unable to get dependency releases during CI/CD pipeline

---

Actions/AL-Go-Helper.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/AddExistingAppOrTestApp.yaml
Templates/AppSource App/.github/workflows/CreateApp.yaml
Templates/AppSource App/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
Templates/AppSource App/.github/workflows/CreatePerformanceTestApp.yaml
Templates/AppSource App/.github/workflows/CreateTestApp.yaml
Templates/AppSource App/.github/workflows/IncrementVersionNumber.yaml
Templates/Per Tenant Extension/.github/workflows/AddExistingAppOrTestApp.yaml
Templates/Per Tenant Extension/.github/workflows/CreateApp.yaml
Templates/Per Tenant Extension/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
Templates/Per Tenant Extension/.github/workflows/CreatePerformanceTestApp.yaml
Templates/Per Tenant Extension/.github/workflows/CreateTestApp.yaml
Templates/Per Tenant Extension/.github/workflows/IncrementVersionNumber.yaml

The following workflows:
- Create New App
- Create New Test App
- Create New Performance Test App
- Increment Version Number
- Add Existing App
- Create Online Development Environment
All uses the Direct COMMIT pattern.
This pattern ignores the branch selected in the run workflow - and always targets main (actually the code runs from the branch selected, targetting main)
This PR fixes this and creates a direct commit or a PR against the selected branch.
It also adds the target branch to the title of the workflow (run_name)
It looks like:
leading to:
and:

Create New App and other workflows ignores selected branch

---

Actions/AL-Go-Helper.ps1
Actions/DetermineArtifactUrl/DetermineArtifactUrl.Action.ps1
Actions/DetermineArtifactUrl/action.yaml
Templates/AppSource App/.github/workflows/CICD.yaml
Templates/AppSource App/.github/workflows/Current.yaml
Templates/AppSource App/.github/workflows/NextMajor.yaml
Templates/AppSource App/.github/workflows/NextMinor.yaml
Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/Current.yaml
Templates/Per Tenant Extension/.github/workflows/NextMajor.yaml
Templates/Per Tenant Extension/.github/workflows/NextMinor.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml

The new DetermineArtifactUrl action, doesn't determine the ApplicationDependency based on the apps in the project - instead it returns the default from the settings if UpdateDependencies is set to true.
When UpdateDependencies is set to true, it needs to find the first compatible artifact matching the app dependencies in the project.

ApplicationDependency is not calculated

---

Actions/AddExistingApp/AddExistingApp.ps1
Actions/Deploy/Deploy.ps1
RELEASENOTES.md

When deploying to online environments in deploy.ps1, it should exclude runtime packages as these cannot be deployed to online environments.
Also fixing a small spelling mistake.

Issue #542

---

Actions/Deliver/Deliver.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml

Publish to AppSource doesn't support national characters in Publisher or App Name.
`+ 2 other places where UTF8 isn't specified when reading a settings file.

National characters

---

Actions/CreateReleaseNotes/CreateReleaseNotes.ps1
Actions/CreateReleaseNotes/README.md
Actions/CreateReleaseNotes/action.yaml
Actions/Github-Helper.psm1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/CreateRelease.yaml
Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml
Tests/CreateReleaseNotes.Test.ps1

Fix for Issue #559 
The created release notes contains all notes - not just to the target committish.

support target_commitish in Release Notes

---

Actions/ReadSettings/ReadSettings.ps1
RELEASENOTES.md

Fix for issue #558
The problem here was, that if the environment was defined in GitHub, then AL-Go would assume that branch policies was defined on the environment and select all branches itself - waiting for GitHub to reject the branch.
The problem with this approach is that if you have a Teams or Enterprise SKU, then the environment will be auto-created when deploying the first time (even if defined in settings).
The fix for this is to only rely on GitHub branch policies if they actually are defined - else use the default branch policies.

Use GitHub environment branch policies (only if defined)

---

Templates/AppSource App/.github/workflows/_BuildALGoProject.yaml
Templates/Per Tenant Extension/.github/workflows/_BuildALGoProject.yaml

When moving to reusable workflows, we forgot to update a reference to matrix. Therefore the sign action is throwing: 
`Error: Sign action failed. Error: Cannot find path 'D:\.buildartifacts\Apps' because it does not exist. Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\Sign\Sign.ps1: line 36 at <ScriptBlock>, D:\a\_temp\41c73416-43db-4b6c-9797-1aae7a7ca5eb.ps1: line 3 at <ScriptBlock>, <No file>: line 1`
Updating the pathToFiles to get the project name from inputs. Tested here: https://github.com/aholstrup1/ALAppExtensions/actions/runs/5483226732

Fix pathToFiles parameter for Sign action

---

Actions/CheckForUpdates/CheckForUpdates.ps1

Issue #575
I did run through a number of tests to see whether this had any impact on API rate limits, which is not the case.

Allow template repos to be private as well as public

---

Actions/CreateApp/AppHelper.psm1
Tests/AppHelper.Test.ps1

Currently, app folders created using the AL Go actions will always be appended at the end of the folder list in the workspace settings. However, for most AL developers, access to the `.github` and `.AL-Go` folders will be low priority. Additionally, some VS Code extensions assume the relevant workspace folder to be the first one, which by default is `.AL-Go`.
When adding a new app, this feature locates both `.github` and `.AL-Go` in the workspace settings, determines which one appears earlier and inserts the newly created app ahead of it. If neither can be found, it will be appended at the end of the list, just like the current behavior.
With this, the first app created will automatically be at first position, with subsequent apps following after.

Add new apps ahead of .github and .AL-Go

---

Actions/AL-Go-Helper.ps1
Actions/CheckForUpdates/CheckForUpdates.ps1
Actions/CreateDevelopmentEnvironment/CreateDevelopmentEnvironment.ps1
Actions/CreateDevelopmentEnvironment/action.yaml
Internal/Deploy.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
Templates/Per Tenant Extension/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml

This PR contains 3 bug fixes:
1. You cannot specify a project in Create Online Development Environment, meaning that it only works in single project repositories and in AppSource Apps it will (in v3.1) give an error, because it doesn't read the project settings file:
https://github.com/freddydk/bcsamples-bingmaps.appsource/actions/runs/5634571925
2. When fixing this bug, I found that the new development mechanism (freddydk/AL-Go@branch) doesn't get the URL for downloading AL-Go-Helper correct. The Update AL-Go System Files will update the URL as this:
- https://raw.githubusercontent.com/freddydk/AL-Go/Actions/branch/AL-Go-Helper.ps1
where it should be:
- https://raw.githubusercontent.com/freddydk/AL-Go/branch/Actions/AL-Go-Helper.ps1
3. Next problem I ran into was that Create Online …

Bug in Create Online Development Environment

---

Actions/AL-Go-Helper.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/AddExistingAppOrTestApp.yaml
Templates/AppSource App/.github/workflows/CreateApp.yaml
Templates/AppSource App/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
Templates/AppSource App/.github/workflows/CreatePerformanceTestApp.yaml
Templates/AppSource App/.github/workflows/CreateRelease.yaml
Templates/AppSource App/.github/workflows/CreateTestApp.yaml
Templates/AppSource App/.github/workflows/IncrementVersionNumber.yaml
Templates/Per Tenant Extension/.github/workflows/AddExistingAppOrTestApp.yaml
Templates/Per Tenant Extension/.github/workflows/CreateApp.yaml
Templates/Per Tenant Extension/.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
Templates/Per Tenant Extension/.github/workflows/CreatePerformanceTestApp.yaml
Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml
Templates/Per Tenant Extension/.github/workflows/CreateTestApp.yaml
Templates/Per Tenant Extension/.github/workflows/IncrementVersionNumber.yaml

This is a fix for issue #555
AL-Go contains several workflows, which create a Pull Request or pushes code directly.
All (except Update AL-Go System Files) will use the GITHUB_TOKEN to create the PR or commit.
The problem using GITHUB_TOKEN is that is doesn't trigger a pull request build or a commit build.
This is by design: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
This PR adds a checkbox to all these actions allowing you to use the GhTokenWorkflow instead of the GITHUB_TOKEN.

Allow using ghTokenWorkflow in workflows creating pull requests (issue555)

---

Actions/CheckForUpdates/CheckForUpdates.ps1
Internal/Collect.ps1
Internal/Deploy.ps1
e2eTests/e2eTestHelper.psm1

When using regex and the substitution pattern has replacements starting with a number (branch, repo, SHA, ...) regex will fail.
This lead to wrong deployment to preview ealier.

Substitution pattern problem

---

Actions/AL-Go-Helper.ps1

Do not output warnings on missing performance tests

Do not output warnings on missing performance tests

---

Actions/DetermineDeploymentEnvironments/DetermineDeploymentEnvironments.ps1
Actions/DetermineDeploymentEnvironments/README.md
Actions/DetermineDeploymentEnvironments/action.yaml
Templates/AppSource App/.github/workflows/PublishToEnvironment.yaml
Templates/Per Tenant Extension/.github/workflows/PublishToEnvironment.yaml
Tests/DetermineDeploymentEnvironments.Test.ps1

Fix for issue #697
Problem was:
- GitHub Environments with a suffix (PROD (PROD)) was not found, leading to publish trying to publish to an unknown environment (because count was 1)
- The autogenerated DeploySettings was missing the EnvironmentType.
But the publish to unknown environment should never be invoked in the first place - only if the environment actually isn't in GitHub - this has also been fixed.

Publish to environment problem in preview

---

Actions/Github-Helper.psm1

Issue 1: after https://github.com/microsoft/AL-Go/commit/7e245d8413b88c59b7d0a05bb4582ac107f99b84#diff-8b3bc43d627973d00981a6cb79e54160281d51f7a4a7aee41e856160e9841b24 there was an issue with `$_` not being defined.
Issue 2: `TestApp` mask is transformed to `<buildMode>TestApps` in non-default mode. There are a few lines that needed fixing.
Note: The issue was not caught in E2E tests as there's no test to cover the PR incremental build (where some projects are not built, but instead fetched from a previous build).

Fix issue with getting dependencies in incremental build

---

Actions/AL-Go-TestRepoHelper.ps1

Fix for Issue #700
Keep warning if it is defined in project settings - as this will never be used.

Remove warning when githubRunner is defined in workflow settings files

---

Actions/AL-Go-Helper.ps1

When running localdevenv.ps1 I'm getting the following error:
`
Using BcContainerHelper preview version
Downloading BcContainerHelper preview version from Blob Storage
Using Expand-Archive
Error: Cannot bind argument to parameter 'Path' because it is null.
Stacktrace: at GetBcContainerHelperPath, C:\Users\aholstrup\AppData\Local\Temp\tmpC451.tmp.ps1: line 370
at DownloadAndImportBcContainerHelper, C:\Users\aholstrup\AppData\Local\Temp\tmpC451.tmp.ps1: line 410
at CreateDevEnv, C:\Users\aholstrup\AppData\Local\Temp\tmpC451.tmp.ps1: line 1516
at <ScriptBlock>, C:\Users\aholstrup\Documents\Github\Microsoft\BCApps\Projects\System Application\.AL-Go\localDevEnv.ps1: line 125
at <ScriptBlock>, <No file>: line 1
`
It appears to happen when we try to write BcContainerHelperPath to …

Check if GITHUB_ENV exists before writing to it

---

Actions/DetermineArtifactUrl/DetermineArtifactUrl.ps1
Actions/RunPipeline/RunPipeline.ps1

```
BC.HelperFunctions emits usage statistics telemetry to Microsoft
AL-Go action ran: DetermineArtifactUrl Telemetry Correlation Id: 76ecbed3-aa21-4f63-8558-278d39cae9f2
Error: Unexpected error when running action. Error Message: Cannot bind argument to parameter 'InputObject' because it is null., StackTrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go\ce6a36367580e96a[44](https://github.com/microsoft/ALAppExtensions/actions/runs/6244972353/job/16952777632?pr=24858#step:5:46)bbc3b5dd31238d945cf8fe\Actions\DetermineArtifactUrl\DetermineArtifactUrl.ps1: line 19 <- at <ScriptBlock>, D:\a\_temp\b7850c6d-56c1-4fb7-a6cc-ee9b1ce4f5f6.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.
```

Add defensive checks for env Secrets 

---

Actions/RunPipeline/RunPipeline.ps1

CompanyName parameter defines the company where tests should be run, but it does not affect test data import.
I suggest adding this modification so companyName setup works for both steps.

use companyName setting on UploadImportAndApplyConfigPackageInBc

---

Actions/AL-Go-Helper.ps1

`PreCompileApp` and `PostCompileApp` are arguments of [Run-AlPipeline](https://github.com/microsoft/navcontainerhelper/blob/master/AppHandling/Run-AlPipeline.ps1) in BCContainerHelper.

Propagate PreCompileApp and PostCompileApp arguments from BCContainerHelper

---

Actions/AL-Go-Helper.ps1
Templates/AppSource App/.AL-Go/localDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1

When I run localdevenv from latest preview I get the following:
_No performance test apps found in bcptTestFolders in .AL-Go\settings.json
Checking appDependencyProbingPaths
Error: The variable '$repo' cannot be retrieved because it has not been set.
Stacktrace: at CreateDevEnv, C:\Users\UserName\AppData\Local\Temp\tmp71A1.tmp.ps1: line 1647_
**Suggested fix**
Getting artifact from $settings.artifact rather than $repo.artifact 
Additionally, add an option to accept insider eula when invoking localdevenv

Get artifact from settings during localdevenv

---

Actions/ReadSecrets/ReadSecretsHelper.psm1
RELEASENOTES.md

Check that C:\Modules (exists on GitHub hosted windows runners) exists before enumerating it.

Bug fix for using self-hosted runners while having an Azure KeyVault connection

---

Actions/AL-Go-Helper.ps1
RELEASENOTES.md
Templates/AppSource App/.AL-Go/cloudDevEnv.ps1
Templates/AppSource App/.AL-Go/localDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/cloudDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1

and add some information about URLs in output.
and ensure that the version.txt file isn't locked (and the folder can be renamed)
and prettify the output
Fix for issues found when investigating #739

Add WorkflowName in localDevEnv

---

Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml

Issue: when only .md files are changed, the _PR Build_ is not triggered, thus _PR Status Check_ stay pending, causing the PR to be unmergeable (in the cases where _PR Status Check_ is required).

Run PR Build even when only MD files are changed 

---

.github/workflows/Deploy.yaml
Internal/Deploy.ps1

After finding out that v3.3 was shipped with containerHelper preview as the selected version, I investigated and found that:
If a defaultContainerHelperVersion wasn't specified when running deploy, the default containerHelperVersion used was taken from AL-Go-Helper.ps1 (which normally is "preview")
This PR defaults defaultContainerHelperVersion to preview for preview branches and latest for other branches.
Also it makes sure that the line in AL-Go-Helper.ps1 can be found and patched - else it will throw an error.

Fix containerhelperversion in deploy

---

Actions/AnalyzeTests/AnalyzeTests.ps1
Templates/AppSource App/.github/workflows/_BuildALGoProject.yaml
Templates/Per Tenant Extension/.github/workflows/_BuildALGoProject.yaml

GitHub will only show the first three build summaries and showing "Test Results Not Found" three times doesn't provide much value IMO. 
Only display test result summary when there is something to display

Only display test result summary when there is something to display 

---

Actions/AL-Go-Helper.ps1
Actions/RunPipeline/RunPipeline.ps1

When getting event log in single project repositories, the following message is written to the log as info:
Error getting event log from container: Cannot overwrite the item D:\a\GHP-DK\GHP-DK\ContainerEventLog.evtx with itself.
This PR removes this error-info

Avoid error-info getting event log

---

Actions/CalculateArtifactNames/CalculateArtifactNames.ps1
Actions/CalculateArtifactNames/README.md
Actions/CalculateArtifactNames/action.yaml
Actions/Github-Helper.psm1
Actions/RunPipeline/RunPipeline.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/_BuildALGoProject.yaml
Templates/Per Tenant Extension/.github/workflows/_BuildALGoProject.yaml
Tests/CalculateArtifactNames.Test.ps1

Fixes #823 
This pull request includes changes related to the handling of dependencies artifacts in several files. The most important changes include adding a new step to upload dependencies artifacts, modifying the `if` condition for uploading dependency artifacts, and updating the `GetDependencies` function to include the dependencies folder in its search for dependencies.
Dependency handling changes:
* `Templates/Per Tenant Extension/.github/workflows/_BuildALGoProject.yaml`: Added a new step to upload dependencies artifacts and added the `generateDependencyArtifact` input to the `get` parameter in two jobs. (F1a2b3c4R1)
* `Actions/Github-Helper.psm1`: Updated the `GetDependencies` function to include the dependencies folder in its search for dependencies. (F2d3e4f5R1)
* …

Dependencies from prior build jobs are not included when using useProjectDependencies

---

Actions/AL-Go-Helper.ps1
Actions/RunPipeline/RunPipeline.ps1
RELEASENOTES.md

Utilize useCompilerFolder when creating dev env

---

Actions/AL-Go-Helper.ps1

_**Issue**_: When a developer environment is created, the location is set to the AL-Go project's folder and then never set back to the original location
_**Solution**_: Always set back the previous location when creating a dev env.

Pop location after creating dev env

---

Actions/Github-Helper.psm1

_Issue_:
A CICD workflow run with no build jobs is considered _successful_.
_Solution_:
Check if the CICD has at least one build job.

Consider CICD workflow run with no build jobs unsuccessful

---

Actions/AnalyzeTests/TestResultAnalyzer.ps1

In the **Build . - Default / . - Default summary** section of an action results I see `:white_check_mark:` instead of :white_check_mark::
separate a number and the smile by a space:
- "$($appPassed) :white_check_mark:"
- "$($appFailed) :x:"  
- "$($appSkipped) :white_circle:"

Added missing space to make :white_check_mark: visible as a pic

---

Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1
Actions/CreateReleaseNotes/CreateReleaseNotes.ps1
Actions/CreateReleaseNotes/README.md
Actions/CreateReleaseNotes/action.yaml
Actions/Github-Helper.psm1
Actions/ReadSettings/ReadSettings.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/CICD.yaml
Templates/AppSource App/.github/workflows/CreateRelease.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml
Tests/CreateReleaseNotes.Test.ps1

Support release branches that start with "releases/"

Support release branches that start with "releases/"

---

Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1
Actions/CheckForUpdates/yamlclass.ps1
RELEASENOTES.md
Tests/CheckForUpdates.Action.Test.ps1

Add support for `UpdateALGoSystemFilesEnvironment` setting in order to set the [environment](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment) property of the `UpdateALGoSystemFiles` job.

Add support for UpdateALGoSystemFilesEnvironment setting

---

Actions/Github-Helper.psm1

After https://github.com/microsoft/AL-Go/commit/bf1e8f35935cb9a2361a40e47b6bf3a2ec0dad9c#diff-8b3bc43d627973d00981a6cb79e54160281d51f7a4a7aee41e856160e9841b24 getting the release branch version from the branch name was broken.
Fix for failing E2E test: https://github.com/microsoft/AL-Go/actions/runs/7637020651/job/20805106171

Fix getting version from a release branch name

---

Scenarios/SelfHostedGitHubRunner.md

fix SelfHostedGitHubRunner.md

---

Actions/AL-Go-Helper.ps1
Actions/BuildReferenceDocumentation/BuildReferenceDocumentation.HelperFunctions.ps1
Actions/Github-Helper.psm1
RELEASENOTES.md
Scenarios/UpdateAlGoSystemFiles.md

Give better error message if GitHub CLI or GIT isn't installed

---

.github/workflows/powershell.yaml

Fixes #928
See: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

Bump github/codeql-action/upload-sarif to v3

---

Actions/AL-Go-Helper.ps1

AL-GO doesn't apply conditional settings on PR Builds. In BCApps we have the following conditional setting in the project settings 
```
"buildModes": [ "Translated" ],
"ConditionalSettings": [
{
"branches": [
"releases/*.[0-5]"
],
"settings": {
"buildModes": [ "Translated", "Strict"]
}
}
]
```
Yet when you see the PR builds, it doesn't build in StrictMode: 
https://github.com/microsoft/BCApps/actions/runs/8044365490
In ReadSettings we only apply conditional settings if the branchname matches the pattern in the setting. The problem is that the branchName is set to GITHUB_BASE_REF which for PR builds triggered by the pull_request trigger is the merge branch (e.g. refs/heads/merge/123). The branch pattern for the conditional setting will therefore never match on PR Builds.

Applying conditional settings for PR Builds

---

Actions/Github-Helper.psm1
RELEASENOTES.md
e2eTests/e2eTestHelper.psm1

Fixes #973
The fix can best be illustrated by running this code:
```powershell
@('[]' | ConvertFrom-Json).Count
@('[{"a":"1"}]' | ConvertFrom-Json).Count
@('[{"a":"1"},{"b":"2"}]' | ConvertFrom-Json).Count
```
Returns: 1, 1, 1
Expected: 0,1,2
Where this:
```powershell
('[]' | ConvertFrom-Json).Count
('[{"a":"1"}]' | ConvertFrom-Json).Count
('[{"a":"1"},{"b":"2"}]' | ConvertFrom-Json).Count
```
Returns: 0,1,2 as expected

fix array cast

---

RELEASENOTES.md
Templates/AppSource App/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml

"Determine Deployment Environment" relies on the GITHUB_TOKEN to see if github pages is enabled. To do this it needs at least pages: read permission. 
Right now CI/CD doesn't define any permissions for "pages". This is fine for public repos but fails for private ones seemingly. 
Related to #994

Add pages read permission to CICD

---

Templates/AppSource App/.github/workflows/CICD.yaml
Templates/AppSource App/.github/workflows/DeployReferenceDocumentation.yaml
Templates/AppSource App/.github/workflows/_BuildALGoProject.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/DeployReferenceDocumentation.yaml
Templates/Per Tenant Extension/.github/workflows/_BuildALGoProject.yaml

Deploy Reference Documentation is currently given `contents: write` permission but it doesn't seem to need it. These workflows succeeded with `contents: read` permission
https://github.com/aholstrup1/BCApps/actions/runs/8538607739
https://github.com/aholstrup1/BCApps/actions/runs/8535969767
This PR would lower that permission and explicitly add top-level permissions for the _BuildALGoProject reusable workflow 
See also results on https://github.com/microsoft/BCApps/security/code-scanning for more info on why we'd like to lower these permissions of possible :)

Update permissions for Deploy Reference Documentation and add permissions for _BuildALGoProject

---

Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml
Tests/WorkflowSanitation/WorkflowFileContent.Test.ps1

Fixes #1008
Allow Update AL-Go System Files to update runs-on in PullRequestHandler.yaml, except for PregateCheck.
PregateCheck is set to use runs-on: windows-latest which will not be updated.
Update AL-Go System Files will update occurances of "runs-on: [ windows-latest ]" with "runs-on: [ (runs-on setting) ]"

Allow PullRequestHandler to use ubuntu-latest

---

Actions/IncrementVersionNumber/IncrementVersionNumber.psm1
RELEASENOTES.md
Tests/IncrementVersionNumber.Action.Test.ps1

Use new variable in `Set-VersionInSettingsFile` as variable type isn't changed.
_**Issue**_:
`$newValue` is of type string by default. 
The assignment `$newVersion = [System.Version] "$($versionNumbers -join '.')"` doesn't change the variable's type and forces string comparison afterwards.
_**Solution**_: Use new variable.
Fixes #1041

Use new variable in Set-VersionInSettingsFile

---

Actions/WorkflowInitialize/README.md
Actions/WorkflowInitialize/WorkflowInitialize.ps1
Actions/WorkflowInitialize/action.yaml

AL-Go version is not displayed correctly in WorkflowInitialize
Example (when using the AL-Go PPPreview)
When running Linux it would fail, but swallow the exception

AL-Go version in WorkflowInitialize

---

Templates/AppSource App/.github/workflows/PublishToEnvironment.yaml
Templates/Per Tenant Extension/.github/workflows/PublishToEnvironment.yaml

This PR changes the "Publish To Environment" workflows of both the PTE and AppSource templates.
With this fix, all steps of the "Deploy" job now use the deployment matrix to determine the value of the `shell` property of each step.
Fixes #1101

Use matrix for shell value in PublishToEnvironment.yaml

---

Actions/AL-Go-Helper.ps1
Actions/CheckForUpdates/CheckForUpdates.ps1

Fixes #1092
The logic for showing release notes in the Update AL-Go for GitHub PR hasn't been working for a while.
This PR also includes info about which template is used in the PR name

Update releasenotes logic

---

Templates/AppSource App/README.md
Templates/Per Tenant Extension/README.md

GitHub removed the Use this template button - this PR adds it in the README.md
Fixes #1125

Add Use this template button

---

Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml

**Problem**
With `github.event.pull_request.merge_commit_sha` we're not guaranteed to get all the latest changes from the head branch included in the build. Often we only get the changes from the second last commit https://github.com/actions/checkout/issues/518#issuecomment-1757453837
Previously we used the merge branch but with the merge branch it's possible to push new changes to a PR from a forked repo and have the PR Build run on unapproved changes. 
**Proposed Solution**
Use Github SHA if possible in the PR Build. Otherwise use the merge branch. 
The [pull_request](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) trigger will use the github_sha which is the last merge commit on the GITHUB_REF branch. Thereby it should not be possible for …

Pull Request Handler - Use Github SHA if possible

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.yaml
.github/ISSUE_TEMPLATE/question.yaml

Adding some issue forms to AL-Go. You can see how it will look here: https://github.com/aholstrup1/AL-Go/issues/new/choose

Add issue forms to AL-Go

---

RELEASENOTES.md
Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml

This PR fixes an error introduced by #1130.
The new reference values use the `format()` command to generate a git reference, but the placeholder syntax was incorrect.
The two instances of `${0}` per template have been replaced with `{0}`.

Fix placeholder syntax in PR Handler action

---

.github/workflows/E2E.yaml
Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1
Actions/CheckForUpdates/CheckForUpdates.ps1
RELEASENOTES.md
e2eTests/Test-AL-Go.ps1
e2eTests/e2eTestHelper.psm1
e2eTests/scenarios/BuildModes/runtest.ps1
e2eTests/scenarios/FederatedCredentials/runtest.ps1
e2eTests/scenarios/GitHubPackages/runtest.ps1
e2eTests/scenarios/IncludeDependencies/runtest.ps1
e2eTests/scenarios/PowerPlatform/runtest.ps1
e2eTests/scenarios/ReferenceDocumentation/runtest.ps1
e2eTests/scenarios/ReleaseBranches/runtest.ps1
e2eTests/scenarios/SpecialCharacters/runtest.ps1
e2eTests/scenarios/UseProjectDependencies/runtest.ps1

This pull request adds a check to allow updating the `runs-on` and `shell` parameters of all workflows. Previously, the workflows "Update AL Go System Files" and "Pull Request Handler" were excluded when changing the two parameters to prevent deadlocks and security issues.
With this change, a check will only allow changing the parameters of the blacklisted workflows if the `runs-on` parameter is either `windows-latest` or `ubuntu-latest`. Additionally, a check in the function `ModifyRunsOnAndShell` ensures only the value `pwsh` is allowed when using an `ubuntu-latest` runner.

Allow "ubuntu-latest" runners for all workflows

---

Templates/AppSource App/.github/workflows/PullRequestHandler.yaml
Templates/Per Tenant Extension/.github/workflows/PullRequestHandler.yaml

WorkflowPostProcess only runs on successful PR Builds. This is a problem for telemetry because we use the WorkflowPostProcess action to emit the "AL-Go workflow ran/failed" telemetry. Therefore, we're not emitting that telemetry right now when PR Builds are failing. 
See for example: https://github.com/microsoft/BCApps/actions/runs/10315611720/job/28556490157

WorkflowPostProcess only runs on successful PR Builds 

---

Actions/WorkflowPostProcess/README.md
Actions/WorkflowPostProcess/WorkflowPostProcess.ps1
Actions/WorkflowPostProcess/action.yaml

Update how AL-Go version is determined. 
Since $ENV:GITHUB_REPOSITORY is the repository that runs the workflow, AL-Go version will always be "Developer/Private" unless the workflow is being run from a Microsoft-owned repo.

Update how AL-Go version is determined

---

RELEASENOTES.md
Templates/AppSource App/.github/workflows/PublishToEnvironment.yaml
Templates/Per Tenant Extension/.github/workflows/PublishToEnvironment.yaml

Do not use matrix shell in postprocess job as the job is not a matrix
Related to #1184

Do not use matrix shell in postprocess job

---

Actions/IncrementVersionNumber/IncrementVersionNumber.psm1
RELEASENOTES.md

**Problem**
When incrementing the version number in our repo, one of the dependency apps were given two version entries. 
https://github.com/microsoft/BCApps/pull/2152/commits/c4d59f07901fb4c0f4dcaba5a5b48789a67ec624
**Solution**
* Gather app infos by iterating over the distinct app folders 
* If multiple app ids are found, select the first one

Increment Version Number might produce wrong app.json 

---

Actions/Packages.json
Actions/Sign/Sign.psm1

* Update the Sign script to log the output of dotnet install to the logs. 
* Update the sign package to latest. The Sign team recently made an improvement to write a warning if _Visual C++ Runtime_ is not installed. If it isn't, signing will fail because NavSip depends on this assembly.  
Related to #1252

Write output of sign install to log

---

e2eTests/e2eTestHelper.psm1
e2eTests/scenarios/FederatedCredentials/runtest.ps1

The new sign tool returns
`Signing C:\Users\runneradmin\AppData\Local\Temp\5kjwvcol.khn\sv3h0r4d.app succeeded.`
instead of 
`Signing succeeded.`

End 2 End Test Failure

---

Actions/AL-Go-Helper.ps1
Actions/CheckForUpdates/CheckForUpdates.ps1
RELEASENOTES.md

This pull request introduces a new function to output notices and updates existing scripts to use this function instead of issuing warnings when there are no updates available for AL-Go for GitHub.
New function addition:
* [`Actions/AL-Go-Helper.ps1`](diffhunk://#diff-d6e7039af6c0c11ad1a23decab42e0c9d1faeb7756089f0ebf640a2694665014R188-R200): Added `OutputNotice` function to output messages as notices.
Updates to existing scripts:
* [`Actions/CheckForUpdates/CheckForUpdates.ps1`](diffhunk://#diff-263c4046164f3ede51bbb35b7cdaf06701d35691bf18971273f24eaeb9bd41edL201-R201): Updated to use `OutputNotice` instead of warnings when no updates are available.
Documentation update:
* [`RELEASENOTES.md`](diffhunk://#diff-310cf8dbf9f6a843674df7afb82cf592a81636c01f7c25221aba39cf86e8dcf1R7): Added an …

Output a notice when there are no available updates for AL-Go

---

Actions/AL-Go-Helper.ps1

Current Update AL-Go System files is failing on BCApps: 
https://github.com/microsoft/BCApps/actions/runs/12389564864
When invoking gh-cli it throws the error: 
`unknown arguments ["appFolders optional\n- Issue 1344 Experimental feature git" "submodules seems to be a breaking change\n- Issue 1305 Extra telemetry Property RepositoryOwner and RepositoryName¨\n- Add RunnerEnvironment to Telemetry\n- Output a notice, not a warning, when there are no available updates for AL-Go for GitHub\n\n### New Repository Settings\n\n- useGitSubmodules can be either \true or \recursive if you want to enable Git Submodules in your repository. If your Git submodules reside`
Error most likely stems from unescaped characters in the release notes. 
Update PR Create command to not use Invoke-Expression

Update PR Create command to not use Invoke-Expression

---

.devcontainer/devcontainer.json
Scenarios/Contribute.md

Add a devcontainer.json file to install pre-commit and BCContainerHelper to make AL-Go development from codespaces easier.

Add support for AL-Go development in GitHub codespaces 

---

RELEASENOTES.md

- `cleanModePreprocessorSymbols` will be removed after April 1st 2025. Use [Conditional Settings](https://aka.ms/algosettings#conditional-settings) instead, specifying buildModes and the `preprocessorSymbols` setting. Read [this](https://aka.ms/algodeprecations#cleanModePreprocessorSymbols) for more information.

fix releasenotes

---

Actions/Github-Helper.psm1

When locating project dependencies and no Dependencies artifact is present - no TestApps will be searched for because the project will be marked as not built.
Fixes #1338

Multi-Project Repository Test App Dependencies Not Resolved

---

Actions/AL-Go-Helper.ps1
Actions/RunPipeline/RunPipeline.ps1
Actions/TelemetryHelper.psm1

Log telemetry for uses of deprecated features

Log telemetry for uses of deprecated features

---

Templates/AppSource App/.github/workflows/IncrementVersionNumber.yaml
Templates/Per Tenant Extension/.github/workflows/IncrementVersionNumber.yaml

The workflow fails in private repos if top-level (workflow-level) permissions are defined.

Remove top-level permissions in IncrementVersionNumber workflow

---

Actions/Deliver/Deliver.ps1
Actions/Deliver/README.md
Actions/Deliver/action.yaml
Actions/DetermineDeliveryTargets/DetermineDeliveryTargets.ps1

Fix the following warnings from PSScriptAnalyzer:
- The parameter 'projectsJson' has been declared but not used (Actions/DetermineDeliveryTargets/DetermineDeliveryTargets.ps1:3)
- The parameter 'actor' has been declared but not used. (Actions/Deliver/Deliver.ps1:3)

Fix PSScriptAnalyzer warning

---

Actions/AL-Go-Helper.ps1
Actions/RunPipeline/RunPipeline.ps1
RELEASENOTES.md

Fixes #1330
Fixes #1268
This requires a new version of BcContainerHelper with https://github.com/microsoft/navcontainerhelper/pull/3832 for the bugs to be fixed. It will still work like before with the old version.
This PR makes sure that the installed apps, the platform and the country are transferred to NuGet resolution when locating apps for downloading - making sure that you don't download a package with dependencies to BC which is newer than what you are building for.

CompilerFolder doesn't transfer installed Apps to NuGet resolution

---

Actions/ReadSettings/ReadSettings.ps1

Steps to reproduce:
1. Create a PTE app from a template (and add an app)
2. Specify the "versioningStrategy": 7 setting in the ALGoRepoSettings repository variable.
The Read Settings step fails with the following error:
`Error: Unexpected error when running action. Error Message: The variable '$versionStrategy' cannot be retrieved because it has not been set.`
Link to the job run: https://github.com/ashirokikh/pte-bc-app/actions/runs/13445999964/job/37571346317
After the fix is applied, the error message variable is displayed in the logs. The error message is as follows:
`Error: Unknown versioning strategy 7`
Link to the job run: https://github.com/ashirokikh/pte-bc-app/actions/runs/13446113979/job/37571703584

Fix error message when versioning strategy is unknown

---

Actions/AL-Go-Helper.ps1
Actions/DetermineDeploymentEnvironments/DetermineDeploymentEnvironments.ps1
RELEASENOTES.md

Today, the runs-on type in settings must be a string (can be a comma separated number of runner tags) and the runs-on property under environment needs to be an array of strings = runner tags.
This PR makes the runs-on under Environments become a string as well, but support arrays, to not break old settings files.
Fixes #1182
FIxes https://www.yammer.com/dynamicsnavdev/threads/3172600716926976
This means that this setting:
Yields identical os settings in environment matrix json:
```
EnvironmentsMatrixJson={"matrix":{"include":[{"environment":"TEST","os":"[\"windows-latest\",\"windows-2022\"]","shell":"powershell"},{"environment":"TEST2","os":"[\"windows-latest\",\"windows-2022\"]","shell":"powershell"}]},"fail-fast":false}
```
The PR also ensures that shell becomes pwsh if runs-on is …

runs-on type is ambiguous

---

Actions/CheckForUpdates/CheckForUpdates.ps1
Templates/AppSource App/.github/workflows/CICD.yaml
Templates/AppSource App/.github/workflows/CreateRelease.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml

Fixes #1475
By making sure that a GhTokenWorkflow is used (either as PAT or as App Auth) when reading the template.
If the Token doesn't have access to the remove tepo - it will retry with anonymous

fix internal template problem

---

Actions/DetermineProjectsToBuild/DetermineProjectsToBuild.Action.ps1
Actions/DetermineProjectsToBuild/DetermineProjectsToBuild.psm1
Actions/RunPipeline/RunPipeline.ps1
Templates/AppSource App/.github/workflows/_BuildALGoProject.yaml
Templates/Per Tenant Extension/.github/workflows/_BuildALGoProject.yaml
Tests/DetermineProjectsToBuild.Test.ps1

It can be hard to discover the reason why a full build was triggered deep inside the log.
This PR adds a notice to the build when a full build is triggered, with the reason behind it.
Fixes #1487
Additionally, a Pull Request, which should trigger a full build (due to files changed) wouldn't trigger the change due to a parameter error.
Thirdly - in some cases, we would attempt to do a git diff with an empty sha.
Lastly - skip the build cleanup step if no build step was ever run (saves ~10 seconds)

Fix incremental build problems

---

Actions/RunPipeline/RunPipeline.ps1

$downloadedAppsByType was incorrectly initialized as an object instead of a list.
This failed because checking if the object exist in an if statement, will return true for an empty object, but false for a list.

FIx issue with removal of pre-built apps.

---

Templates/AppSource App/.github/workflows/CreateRelease.yaml
Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml

Fixes #1475 (hopefully completely this time)
My apologies Freddy, but I think I messed up when I tested #1477...
CI/CD worked just as intended, but "Create Release" did not work. It ended up with a 404 error. It seemed as if the token sent to the CreateRelase action was empty:
```
_actor: jwikman
_token:                                            <----------
_templateUrl: https://github.com/[redacted]/AL-Go-PTE@preview
_downloadLatest: true
_update: N
_updateBranch: main
_directCommit: false
```
After the proposed change, the token is passed as expected
```
_actor: jwikman
_token: ***                                     <---------------------
_templateUrl: https://github.com/[redacted]/AL-Go-PTE@preview
_downloadLatest: true
_update: N
_updateBranch: main
_directCommit: false
```
I do not …

fix: Use ghTokenWorkflow for CheckForUpdates in CreateRelease.yaml

---

Actions/Deploy/Deploy.ps1

I found a problem, which occured as a result of this PR: https://github.com/microsoft/AL-Go/pull/1437
Causing logs like:
Where known dependencies are not considered when calculating unknown dependencies - (I should have seen that in code review).
This PR fixes this, and the log looks like:

During deployment, known dependencies are considered unknown

---

Actions/AL-Go-Helper.ps1
RELEASENOTES.md
Scenarios/settings.md

BcContainerHelper settings was only read from .github/AL-Go-Settings.json, not allowing global settings in ALGoOrgSettings for TrustedNuGetFeeds, MemoryLimit and other things that should be possible to define globally
Added release notes for the bug fixes checked in yesterday

use settings for BCCH

---

Actions/ReadSecrets/ReadSecrets.ps1
Actions/ReadSecrets/ReadSecretsHelper.psm1
Actions/RunPipeline/RunPipeline.ps1
RELEASENOTES.md

Legacy code signing stopped working
Base64 version of the encrypted version of secrets could be visible in the log. The secret would not be exposed as by using Base64 decoding you would get the encrypted version of the secret, which only can be decrypted on the runner on which it was encrypted - only if you have access to run code on that machine, you would be able to decrypt the secret.

Legacy code signing

---

.github/workflows/Deploy.yaml
Internal/Deploy.ps1

Rather than using a PAT to deploy AL-Go we should support deploying using a GitHub app.

Support deploying AL-Go without OrgPAT

---

Actions/Github-Helper.psm1

add TrimEnd("/") to prep of $repository
trailing "/" causes error when downloading artifacts from another repository

Add TrimEnd to GetDependencies in Github-Helper.psm1

---

.github/workflows/E2E.yaml
e2eTests/SetupRepositories.ps1

Use GH_Token rather than passing token as parameter
Current error: 
```
Deploy.ps1: /home/runner/work/AL-Go/AL-Go/e2eTests/SetupRepositories.ps1:27
Line |
27 |  … PSScriptRoot "..\Internal\Deploy.ps1") -config $config -token $e2epat …
|                                                           ~~~~~~
| A parameter cannot be found that matches parameter name 'token'.
```

AL-Go E2E tests - Use GH_Token rather than passing token as parameter

---

.github/workflows/Deploy.yaml
Internal/Deploy.ps1

The PR moves gh auth setup-git up so it is run before trying to clone the repository. Additionally, the PR pins the dependency on actions/create-github-app-token
Related to #1636

Deployment - GitHub app auth and pin dependency

---

Actions/RunPipeline/RunPipeline.ps1
RELEASENOTES.md

When downloading the previous release, the folder is always created.
However, in the case of issue #1630 the path already exists.
Fixes #1630

Create $artifactsFolder only if it doesn't exist

---

Actions/RunPipeline/RunPipeline.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/_BuildALGoProject.yaml
Templates/Per Tenant Extension/.github/workflows/_BuildALGoProject.yaml

Currently we restore the compiler folder into the project folder. In #1640 this caused builds to pick up an appfolder inside the compiler folder because AL-Go will automatically look for folders with an app.json if appFolders isn't specific in AL-Go settings. 
 
Fixes #1640

Move artifactscache to temp folder

---

Actions/AL-Go-Helper.ps1

When running `ReadSettings` within a Linux container the script fails at the `Sort-Object` line in `MergeCustomObjectIntoOrderedDictionary` with the following error:
```
Cannot bind parameter
| 'Culture' to the target. Exception setting \"Culture\": \"Culture is not
| supported. (Parameter 'name')\niv-iv is an invalid culture
| identifier.\": Cannot bind parameter 'Culture' to the target. Exception
| setting \"Culture\": \"Culture is not supported. (Parameter
| 'name')\niv-iv is an invalid culture identifier.\": Exception setting
| \"Culture\": \"Culture is not supported. (Parameter 'name')\niv-iv is an
| invalid culture identifier.\": Culture is not supported. (Parameter
| 'name')\niv-iv is an invalid culture identifier.
```
This is because within containers there's only a limited set of …

fix: use two-letter invariant culture

---

Actions/Deliver/Deliver.ps1
Actions/ReadSecrets/ReadSecrets.ps1
Actions/ReadSecrets/ReadSecretsHelper.psm1
RELEASENOTES.md

Secrets with teminating newlines might be exposed in the log
Fixes #1654 - GithubPackageContext does not work together with trustedNuGetFeeds

GithubPackageContext does not work together with private trustedNuGetFeeds

---

Actions/AL-Go-Helper.ps1
Actions/RunPipeline/RunPipeline.ps1
RELEASENOTES.md

This pull request includes changes to improve the handling of missing dependencies in the `RunPipeline.ps1` script
If an app has a dependency on an app, which is pre-published to the container, you cannot specify that app in installApps, in fact, you cannot install it at all.
This fix enables allows you to have dependencies to microsoft apps (from the current version) without having to add these to installApps - just add the dependency.
Fixes #1530

Dependencies to pre-published apps doesn't work in AL-Go for GitHub

---

Templates/AppSource App/.github/workflows/CICD.yaml
Templates/AppSource App/.github/workflows/UpdateGitHubGoSystemFiles.yaml
Templates/Per Tenant Extension/.github/workflows/CICD.yaml
Templates/Per Tenant Extension/.github/workflows/UpdateGitHubGoSystemFiles.yaml

After adding https://github.com/microsoft/AL-Go/pull/1663, I found out that GITHUB_TOKEN isn't defined when running.

add github_token environment variable

---

.github/workflows/CleanupTempRepos.yaml
.github/workflows/E2E.yaml
Internal/Scripts/RemoveTempRepos.ps1
e2eTests/scenarios/BCApps/runtest.ps1

This PR switches the E2E testing to use a GitHub app for setup and removal of the temp repositories. This is the first part of the work to remove our dependency on the E2EPAT wherever possible. Once this PR is merged, I will start working on using the same GitHub app for running the E2E tests. 
There are some places we will not be able to remove our dependency on the E2EPAT right now, but the goal (for now) is just to remove our dependency on the E2EPAT everywhere we can. 
Related to AB#573954

Use App in E2E tests during setup

---

Actions/CheckForUpdates/CheckForUpdates.ps1
RELEASENOTES.md
Templates/AppSource App/.github/workflows/UpdateGitHubGoSystemFiles.yaml
Templates/Per Tenant Extension/.github/workflows/UpdateGitHubGoSystemFiles.yaml
Tests/CheckForUpdates.Action.Test.ps1

Fixes #1697
Also, modify runs-on in Update AL-Go System Files to `runs-on: windows-latest`, which doesn't get modified when running Update AL-Go System Files - to ensure that people doesn't get into the situation that they need to run Update AL-Go System Files to modify the runner and they cannot because the runner isn't running.
Added a test to ensure that Update AL-Go System Files stays hardcoded to windows-latest

use basic parsing and ensure windows-latest in Update AL-Go System Files

---

.github/workflows/CleanupTempRepos.yaml
e2eTests/scenarios/PowerPlatform/runtest.ps1

* Move power platform scenario to App Auth
* Use the GitHub owner output by GetOwnerForE2ETests during cleanup. Fixes this issue: https://github.com/microsoft/AL-Go/actions/runs/14750830165
The following PRs need to be merged before this one can go in: 
* https://github.com/microsoft/bcsamples-warehousehelper/pull/5
* https://github.com/microsoft/bcsamples-takeorder/pull/13
* https://github.com/microsoft/bcsamples-CoffeeMR/pull/7
Related to [AB#573954](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/573954)

Move power platform scenario to App Auth

---

Actions/AL-Go-Helper.ps1

Fix PSScriptAnalyzer warning:
```
The Variable '_' is an automatic variable that is built into PowerShell, assigning to it might have undesired side effects. If assignment is not by design, please use a different name.
```

Fix PSScriptAnalyzer warning in AL-Go-Helper.ps1

---

Actions/DetermineProjectsToBuild/DetermineProjectsToBuild.psm1
Actions/RunPipeline/RunPipeline.ps1

downloadedAppsByType was added in a previous PR in order to remove downloaded apps from the build folder, and only keep ones that were built. This feature was later removed again, but the variable remained. 
As it is no longer used, and generating a warning, it is getting removed.

Removing downloadedAppsByType variable.

---

Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1
Actions/CheckForUpdates/CheckForUpdates.ps1
Templates/AppSource App/.github/workflows/CreateRelease.yaml
Templates/Per Tenant Extension/.github/workflows/CreateRelease.yaml

ReleaseBranches failed due to .zip files having paths which are too long for Expand-Archive to handle,
Incremental builds failed because the new json schema changed the file by moving the schema to the end of the .json file always and also remove the templateSha setting - set shortly before the updatefiles.

end 2 end test failures

---

RELEASENOTES.md
Scenarios/EnablingTelemetry.md
Scenarios/resources/telemetrydashboard.json

Provide starter template and example kusto queries
Related to #1777

[Telemetry] Provide starter template and example kusto queries

---

.github/workflows/E2E.yaml

Update E2E tests to only run upgrades on supported versions. Versions lower than 5.0 will soon no longer work since they rely on direct access to our storage account (not through AFD)

Update E2E tests to only run upgrades on supported versions

---

RELEASENOTES.md
Templates/AppSource App/.github/workflows/PublishToEnvironment.yaml
Templates/Per Tenant Extension/.github/workflows/PublishToEnvironment.yaml

When using the Pubish to Environment workflow, targeting a PR in a private repo, the flow will fail with a permission issue, as the Github token does not have access to read the PR and PR annotations.
I have updated the permissions of the workflow to allow the Github token to access these.
Issue #1787

Fixed access issue when Publishing from PR in private repo.

---

e2eTests/e2eTestHelper.psm1
e2eTests/scenarios/FederatedCredentials/runtest.ps1

* Refresh E2E access token more aggressively
* Update how app signing is validated

Improve E2E test Stability

---

e2eTests/e2eTestHelper.psm1

Update headers after refreshing token during E2E tests

Update headers after refreshing token during E2E tests 

---

Actions/Deploy/Deploy.ps1
RELEASENOTES.md

The logic for handling PR publishing did not take branch names with slashes into consideration. This fix simple adds .Replace('/','_') to the ref name, similar to how it is done for other scenarios.
Related to issue: #1837

Fix PR build publishing failing when branch name includes a slash

---

Templates/AppSource App/.AL-Go/cloudDevEnv.ps1
Templates/AppSource App/.AL-Go/localDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/cloudDevEnv.ps1
Templates/Per Tenant Extension/.AL-Go/localDevEnv.ps1

The settings schema was recently moved to a new path, but the urls in cloud/local DevEnvs was not updated. This simply point to the new path.

Updating settings schema to new path.

---

Templates/AppSource App/.AL-Go/settings.json
Templates/AppSource App/.github/AL-Go-Settings.json
Templates/Per Tenant Extension/.AL-Go/settings.json
Templates/Per Tenant Extension/.github/AL-Go-Settings.json

Fixing the incorrect schema path in settings files.
Related to issue: #

Settings JSON schema path fix.

---

Actions/GetWorkflowMultiRunBranches/GetWorkflowMultiRunBranches.ps1
RELEASENOTES.md

Avoid fetching tags when getting the branches for multi-branches workflow run.
_Issue_: "Get Workflow Multi-Run Branches" action fails when there are tags with same value but different casing.
_Solution_: Avoid fetching tags when invoking `git fetch`
Related to issue: #1905

Avoid fetching tags when getting the branches for multi-branches workflow run

---

e2eTests/e2eTestHelper.psm1

Fix debug messages output in e2e tests logs:

Fix e2e tests logs with debug messages

---

.github/DISCUSSION_TEMPLATE/ideas.yml

Add GitHub form for discussions. We want to include an optional checkbox that indicates whether there's an interest in contributing the feature to AL-Go for GitHub.

Add GitHub form for discussions 
